### ISSUE TITLE
L shaped fibula surgical guide

### ISSUE THREAD

**Issue by mauigna06** [SlicerIGT/SlicerBoneReconstructionPlanner#38]
I was watching this video and I noticed that the fibula surgical guide does not use a fibula surgical guide base like the one we use (bone matching surface). Instead it has an L shape to support the surgical guide over the fibula bone.
https://youtu.be/oS460dGOkIQ?t=311
https://youtu.be/FTNT92CxCBs?t=188

What do you think about this?

**Comment by mrtig** [comment]
It seems that using just a simple strip as a base would be ok. From my understanding the position along the fibula is not so important. The surgeons know anyway from what region to cut the fibula segments. It's the angles and lengths that are important to get right.
![image](https://user-images.githubusercontent.com/12380462/116083938-e6fbac00-a6a5-11eb-91d3-90f183ef457e.png)

**Comment by mauigna06** [comment]
Thank you for letting us know what you think @mrtig

Here are some other examples:
https://youtu.be/hOhvHimPvcI?t=54
https://youtu.be/hOhvHimPvcI?t=85

What do you think about this @cmfsx?

**Comment by cmfsx** [comment]
@mauigna06 the base will not matter much. It can be of any design the surgeon is comfortable placing on the fibula. It is true that angle and lengths are the most important determinants. When it comes to the placement of the guide on the fibula it does not need to be a 100% match to the VSP.  The placement on the fibula depends mainly on the location of the skin perforators.  I am not sure if you remember that is why i told you in the beginning that before the CT scan is made if we mark the skin perfortor locations with something radiopaque then we will be able to incoperator that info in to the VSP as well.  But this need not be 100 percent accurate placement. The good thing with the way we are working is that during the VSP , since we transforms the actual bone pieces the surgeon can see the morphology of the fibula and decide what would be the best in terms of morphology. The ususual way of placement is by measuring the distance from a landmark.

**Comment by mauigna06** [comment]
I tried to think about how much error incorporates using a flat surgical guide base but I couldn't get to a conclusion.
I don't really know how to make the flat base without altering a bit the position and orientation of the cuts

**Comment by mauigna06** [comment]
A physics engine can be used to simulate L-shaped surgical guides missposition over the fibula and the changes in length of fibula bone segments and changes in angle of the normals of the fibula planes.
For now this simulations are just an idea and not a near future objetive.
